services:
  local:
    build:
      dockerfile: "Dockerfile"
      target: "local"
    ports:
      - "127.0.0.1:${PORT}:8080"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ${CACHE_DIR}
        target: /root/.cache/go-build
    env_file: ".env"
        
  lint:
    image: golangci/golangci-lint:v1
    command: "golangci-lint run -v"
    working_dir: "/app"
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: true

  deploy:
    build:
      dockerfile: "Dockerfile"
      target: "deploy"
    ports:
      - "127.0.0.1:${PORT}:8080"
    env_file: ".env"

