name: Go build and test

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
      - "go.*"
      - "Makefile"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Test
        run: make test

      - name: Build
        run: make build
